# SourceHut Build Manifest
image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
    - nodejs
    - yarn
    - hut
environment:
    site: lixquid.com
    site_alias: lixqu.id
sources:
    - https://github.com/lixquid/lixquid.com
tasks:
    - build: |
          cd *
          cd src/blog
          git fetch
          git reset --hard origin/master
          cd ../..
          yarn install
          yarn build
    - package: |
          cd */dist
          tar czvf ../dist.tgz *
          hut pages publish -d $site ../dist.tgz
          hut pages publish -d $site_alias ../dist.tgz
