image: node

pages:
    stage: deploy
    script:
        - yarn
        - yarn pug .
        - yarn stylus .
        - mkdir .public
        - cp -r * .public
        - mv .public public
    artifacts:
        paths:
            - public
    only:
        - master
