var quotes = [
	"Metal Gear?",
	"This isn't a car",
	"It's like the reverse corkscrew, but you spin me",
	"Certified Penetration Tester",
	"\"I'm still nippy :(\"",
	"\"I should add that to the site footer.\"",
	"ok hello",
	"Software Developers were seen shouting at a bus",
	"Get out of the lift",
	"Achieved with CSS3",
	"I would",
	"it is a mystery",
	"sometimes I wonder if science thinks about me as much as I think about it idk",
	"hue",
	"And away we go",
	"mvp",
	"rip in peace",
	"You are the Dancing Queen<br />Lettuce Scream<br />Holy Submarine",
	"( ͡° ͜ʖ ͡°)",
	"Reticulating Splines",
	"You wouldn't download a website",
	"sitty thing??",
	"Work harder. Get a car.",
	"I solemnly swear I am up to no good.",
	"Game of the Year",
	"Britishname Complicated",
	"nyello",
	"i lied",
	"That's moderately Raven",
	"Snaaaaaaaake!",
	"Not enough minerals",
	"Spawn more Overlords",
	"ayyyyyy",
	"But what is the plural of Haggis?",
	"You're not even a real journalism.",
	"[website intensifies]",
	"*Angrily fixes Bow Tie*",
	"And the crowd goes mild",
	"well, yes",
	"Why does my tea taste like flowers?",
	"> tfw your almonds aren't activated",
	"You have to be there to be not square",
	"\"I'm happy with my Fisher Price sized Return key\"",
	"smell my hair",
	"Best Chick Flick: Chicken Run",
	"how do u face ur problem if ur problem is ur face??",
	"why fall in love when u can fall asleep",
	"*you're",
	"with great power comes great electricity bill",
	"7/11 was a part time job",
	"there was an attempt",
	"u did a do",
	"Be aware of me!",
	"The Alright Wall Of China",
	"You've still got spots!",
	"It was me. I let the dogs out.",
	"Humanity was born without claws, without fangs, without scales.<br />So we forged them in fire and crafted them of steel.",
	"Oh yes, lot's of yeah.",
	"Ah, the Rolls Royce. Truly the Rolls Royce of automobiles.",
	"Geth do not *intentionally* infiltrate.",
	"/dev/null",
	"kill yourself or die trying",
	"well hello there",
	"not so fast mister",
	"yes i'll hold",
	"now playing",
	"music enabled for 009",
	"Have you tried turning it off and on again?",
	"You wouldn't shoot a policeman",
	"0118 999 881 999 119 725.. 3",
	"I'll just put it here with the rest of the fire.",
	"Fire - exclamation mark - fire - exclamation mark - help me - exclamation mark.<br />Looking forward to hearing from you.",
	"I don't know if it's the loss of blood or the melting plastic from the monitor, but I feel great!",
	"Good morning, that's a nice tnetennba.",
	"I'm not a window cleaner!",
	"\"My mum's on Friendface. She has put down her current mood as 'sensual'.\"",
	"Elevator's not worthy.",
	"woomy",
	"They say taupe is very soothing.",
	"This city deserves a better class of criminal.",
	"I'm gonna make this pencil, disappear.",
	"I want... my phone call. I want it. I want it! I want my phone call!",
	"The Lamborghini, then. Much more subtle."
];
document.getElementById( "quote" ).innerHTML = quotes[ Math.floor( Math.random() * quotes.length ) ];
